---
# The image used to start a container to do build jobs, which should has all
# build depencies installed
# coverage: '/total:[\t]*statements[\t]*\d+\.\d+%/'
#  coverage: '/total:[\t]*\(statements\)[\t]*\d+\.\d+%/'

variables:
    {
        JOB_NAME: "${CI_PROJECT_NAME}"
    }

.projecttest: &TEST
    image: ${BUILDIMAGES}
    stage: test
    script:
        - echo "OK"

.projectbuild: &BUILD
    image: ${BUILDIMAGES}
    stage: build
    script:
        - yum install -y zlib-devel
        - cd packaging && make
    artifacts:
        paths:
            - packaging/x86_64/acl-libs-*.rpm
            - packaging/x86_64/acl-master-*.rpm
    only:
      - /^check-.*$/
    except:
        - tags@cdn-cloud/acl

.basepublishdev: &DEVEL
    image: ${BUILDIMAGES}
    stage: publish
    script:
        - yum install -y zlib-devel
        - cd packaging && make
        - cd ${CI_PROJECT_DIR} && /tools/publish.sh
    coverage: '/lines......: \d+\.\d+%/'
    only:
      - /^devel-.*$/
    artifacts:
        paths:
            - packaging/x86_64/acl-libs-*.rpm
            - packaging/x86_64/acl-master-*.rpm

.lib_release: &LIB_RELEASE
    image: ${BUILDIMAGES}
    stage: publish
    script:
        - yum install -y zlib-devel
        - cd packaging && make
        - cd ${CI_PROJECT_DIR} && /tools/publish.sh -t prerelease
    coverage: '/lines......: \d+\.\d+%/'
    only:
        - /^release-.*$/
    artifacts:
        paths:
            - packaging/x86_64/acl-libs-*.rpm
              #- packaging/x86_64/acl-master-*.rpm

.frame_release: &FRAME_RELEASE
    image: ${BUILDIMAGES}
    stage: publish
    script:
        - yum install -y zlib-devel
        - cd packaging && make PKG_NAME=acl-master
        - cd ${CI_PROJECT_DIR} && /tools/publish.sh -t prerelease
    coverage: '/lines......: \d+\.\d+%/'
    only:
        - /^master-.*$/
    artifacts:
        paths:
            - packaging/x86_64/*.rpm

stages:
    - test
    - publish

test:centos:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.2"
    }
    <<: *TEST

devel:centos7.0:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.0"
    }
    <<: *DEVEL

devel:centos7.2:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.2"
    }
    <<: *DEVEL

devel:centos8.0:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:8.0"
    }
    <<: *DEVEL

devel:centos8.2:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:8.2"
    }
    <<: *DEVEL

lib_release:centos7.0:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.0"
    }
    <<: *LIB_RELEASE

lib_release:centos7.2:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.2"
    }
    <<: *LIB_RELEASE

lib_release:centos8.0:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:8.0"
    }
    <<: *LIB_RELEASE

lib_release:centos8.2:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:8.2"
    }
    <<: *LIB_RELEASE

frame_release:centos7.0:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.0"
    }
    <<: *FRAME_RELEASE

frame_release:centos7.2:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:7.2"
    }
    <<: *FRAME_RELEASE

frame_release:centos8.0:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:8.0"
    }
    <<: *FRAME_RELEASE

frame_release:centos8.2:
    variables: {
        BUILDIMAGES:
            "docker-registry.qiyi.virtual/acl/centos-builder:8.2"
    }
    <<: *FRAME_RELEASE
